    {
        "apiVersion": 3,
        "name": "__COMPONENT_NAMESPACE__",
        "title": "__COMPONENT_NAME_TITLE__",
        "category": "design",
        "icon": "__COMPONENT_ICON__",
        "description": "A custom block generated by the Block Factory plugin.",
        "textdomain": "block-factory",
        "supports": {
            "html": false,
            "anchor": true
        },
        "attributes": {
            "default_title": {
                "type": "string",
                "default": "Click 'Edit Structure' to define fields."
            },
            "__INJECT_ATTRIBUTES_HOOK__": {}
        },
        "editorScript": "file:./index.js",
        "style": "file:./style-index.css",
        "editorStyle": "file:./editor.css"
    }