<?php
/**
 * Generator — file regeneration methods only.
 *
 * Block creation/deletion moved to GutenKit_BlockCreator (Task 3).
 * npm build/install moved to GutenKit_BlockBuilder (Task 3).
 *
 * @package GutenKit
 */

if (!defined('ABSPATH')) {
	exit;
}

class GutenKit_Generator
{

	public function __construct()
	{
		// No hooks — this class is called directly by ConfigManager
		// for file regeneration via regenerate_files_from_config().
	}

	/**
	 * Transition bridge: called by ConfigManager to regenerate block files from config.
	 * This method will be removed in Task 5 when file generation moves to Node.js.
	 *
	 * @param string $slug        Block slug.
	 * @param array  $config_data Full merged config data.
	 */
	public function regenerate_files_from_config( $slug, $config_data ) {
		$this->update_block_json( $slug, $config_data );
		$this->regenerate_edit_js( $slug, $config_data );

		// render.php is now generated by Node.js (generate-block-code-multi.js)

		if ( isset( $config_data['css'] ) ) {
			$block_dir   = BLOCKS_BASE_PATH . $slug . '/';
			$style_path  = $block_dir . 'style.scss';
			$css_content = $this->inject_script_base_css( $config_data['css'], $config_data );
			$fs          = $this->get_filesystem();
			if ( $fs ) {
				$fs->put_contents( $style_path, $css_content, FS_CHMOD_FILE );
			} else {
				file_put_contents( $style_path, $css_content );
			}
		}
	}

	// --- Helper Methods ---

	private function update_block_json($block_slug, $config_data)
	{
		$json_path = BLOCKS_BASE_PATH . $block_slug . '/block.json';
		if (!file_exists($json_path)) {
			return;
		}

		$fs         = $this->get_filesystem();
		$raw        = $fs ? $fs->get_contents($json_path) : file_get_contents($json_path);
		$block_meta = json_decode($raw, true);

		if (!isset($block_meta['attributes'])) {
			$block_meta['attributes'] = [];
		}

		foreach ($config_data['fields'] as $field) {
			$key = $field['key'];
			// Check/Update attribute definition
			// We DO overwrite existing definitions to support type changes (e.g. text -> number)
			// checking if isset is bad if user changes field type.

			$type = 'string';
			if (in_array($field['type'], ['number', 'range', 'relational'])) {
				$type = 'number';
			} elseif (in_array($field['type'], ['image', 'file', 'button'])) {
				$type = 'object';
			} elseif (in_array($field['type'], ['repeater', 'gallery'])) {
				$type = 'array';
			}

			$attr_definition = ['type' => $type];
			if ($type === 'array') {
				$attr_definition['default'] = [];
				$attr_definition['items'] = ['type' => 'object'];
			}
			$block_meta['attributes'][$key] = $attr_definition;
		}

		$encoded = json_encode($block_meta, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
		if ($fs) {
			$fs->put_contents($json_path, $encoded, FS_CHMOD_FILE);
		} else {
			file_put_contents($json_path, $encoded);
		}
	}

	private function regenerate_edit_js($block_slug, $config_data)
	{
		$block_dir     = BLOCKS_BASE_PATH . $block_slug . '/';
		$template_path = BLOCK_FACTORY_PATH . 'templates/edit.js.tpl';
		$edit_js_path  = $block_dir . 'edit.js';

		if (!file_exists($template_path)) {
			return false;
		}

		$fs       = $this->get_filesystem();
		$template = $fs ? $fs->get_contents($template_path) : file_get_contents($template_path);
		$fields = $config_data['fields'];
		$block_template = isset($config_data['template']) ? $config_data['template'] : '';

		// 1. Generate Inspector Controls (Sidebar)
		$inspector_controls = $this->generate_inspector_controls($fields);

		// 2. Generate Canvas Preview (HTML)
		$canvas_preview = $this->generate_canvas_preview($block_template, $fields);

		// 3. Imports
		$extra_imports_editor = [];
		$extra_imports_components = ['PanelBody'];

		foreach ($fields as $field) {
			if ($field['type'] === 'text' || $field['type'] === 'textarea') {
				if (!in_array('TextControl', $extra_imports_components))
					$extra_imports_components[] = 'TextControl';
				if (!in_array('TextareaControl', $extra_imports_components))
					$extra_imports_components[] = 'TextareaControl';
			} elseif ($field['type'] === 'image' || $field['type'] === 'file') {
				if (!in_array('MediaUpload', $extra_imports_editor))
					$extra_imports_editor[] = 'MediaUpload';
				if (!in_array('MediaUploadCheck', $extra_imports_editor))
					$extra_imports_editor[] = 'MediaUploadCheck';
				if (!in_array('Button', $extra_imports_components))
					$extra_imports_components[] = 'Button';
			} elseif ($field['type'] === 'range') {
				if (!in_array('RangeControl', $extra_imports_components))
					$extra_imports_components[] = 'RangeControl';
			} elseif ($field['type'] === 'toggle') {
				if (!in_array('ToggleControl', $extra_imports_components))
					$extra_imports_components[] = 'ToggleControl';
			} elseif ($field['type'] === 'color') {
				if (!in_array('ColorPalette', $extra_imports_components))
					$extra_imports_components[] = 'ColorPalette';
			} elseif (in_array($field['type'], ['date', 'datetime'])) {
				if (!in_array('DatePicker', $extra_imports_components))
					$extra_imports_components[] = 'DatePicker';
			} elseif ($field['type'] === 'contentEditor') {
				if (!in_array('RichText', $extra_imports_editor))
					$extra_imports_editor[] = 'RichText';
				if (!in_array('ToggleControl', $extra_imports_components))
					$extra_imports_components[] = 'ToggleControl';
			} elseif ($field['type'] === 'relational') {
				if (!in_array('SelectControl', $extra_imports_components))
					$extra_imports_components[] = 'SelectControl';
			} elseif ($field['type'] === 'gallery') {
				if (!in_array('MediaUpload', $extra_imports_editor))
					$extra_imports_editor[] = 'MediaUpload';
				if (!in_array('MediaUploadCheck', $extra_imports_editor))
					$extra_imports_editor[] = 'MediaUploadCheck';
				if (!in_array('Button', $extra_imports_components))
					$extra_imports_components[] = 'Button';
			}
		}

		// Script injection
		$scripts        = isset( $config_data['scripts'] ) ? $config_data['scripts'] : null;
		$script_import  = $this->get_script_import( $scripts );
		$editor_effect  = $this->generate_editor_effect( $scripts );

		$replacements = [
			'{{BLOCK_SLUG}}' => $block_slug,
			'// __INJECT_BLOCK_EDITOR_IMPORTS__' => !empty($extra_imports_editor) ? ', ' . implode(', ', $extra_imports_editor) : '',
			'// __INJECT_COMPONENTS_IMPORTS__' => !empty($extra_imports_components) ? ', ' . implode(', ', $extra_imports_components) : '',
			'// __INJECT_UI_CODE__' => $inspector_controls,
			'// __INJECT_CANVAS_PREVIEW__' => $canvas_preview,
			'// __INJECT_SCRIPT_IMPORTS__' => $script_import,
			'// __INJECT_EDITOR_EFFECTS__' => $editor_effect,
		];

		$final_js = str_replace(array_keys($replacements), array_values($replacements), $template);
		if ($fs) {
			return $fs->put_contents($edit_js_path, $final_js, FS_CHMOD_FILE) !== false;
		}
		return file_put_contents($edit_js_path, $final_js) !== false;
	}

	const EMBLA_CSS_START = '/* [embla-base:start] */';
	const EMBLA_CSS_END   = '/* [embla-base:end] */';

	/**
	 * Prepends (or replaces) required base CSS in a block's style.scss content.
	 * Uses data-attribute selectors so it works regardless of user class names.
	 */
	private function inject_script_base_css( $user_css, $config_data ) {
		$script_type = isset( $config_data['scripts']['type'] ) ? $config_data['scripts']['type'] : '';

		if ( $script_type === 'slider' ) {
			$base_css = self::EMBLA_CSS_START . "\n"
				. "/* Embla Carousel required base styles — do not edit this block */\n"
				. "[data-embla-viewport] { overflow: hidden; }\n"
				. "[data-embla-viewport] > * { display: flex; touch-action: pan-y pinch-zoom; }\n"
				. "[data-embla-viewport] > * > * { flex: 0 0 100%; min-width: 0; }\n"
				. self::EMBLA_CSS_END . "\n";
		} else {
			$base_css = '';
		}

		// Strip any previously injected base block
		$start_idx = strpos( $user_css, self::EMBLA_CSS_START );
		$end_idx   = strpos( $user_css, self::EMBLA_CSS_END );
		if ( $start_idx !== false && $end_idx !== false ) {
			$after    = substr( $user_css, $end_idx + strlen( self::EMBLA_CSS_END ) );
			$user_css = $start_idx > 0 ? substr( $user_css, 0, $start_idx ) : '';
			$user_css = ltrim( $user_css . $after );
		}

		return $base_css ? $base_css . "\n" . $user_css : $user_css;
	}

	/**
	 * Returns the static import line for the given scripts config (empty string if none needed).
	 */
	private function get_script_import( $scripts ) {
		if ( empty( $scripts['type'] ) ) return '';
		switch ( $scripts['type'] ) {
			case 'slider':
				return "import EmblaCarousel from 'embla-carousel';";
			default:
				return '';
		}
	}

	/**
	 * Returns the useEffect body to inject into the Edit component for the Gutenberg canvas preview.
	 * Uses data-embla-* attributes — class names are irrelevant.
	 */
	private function generate_editor_effect( $scripts ) {
		if ( empty( $scripts['type'] ) ) return '';

		$opts = isset( $scripts['options'] ) ? $scripts['options'] : array();

		switch ( $scripts['type'] ) {
			case 'slider': {
				$loop  = ! empty( $opts['loop'] ) ? 'true' : 'false';
				$align = ! empty( $opts['align'] ) ? esc_js( $opts['align'] ) : 'start';
				return "
	useEffect( () => {
		if ( ! canvasRef.current ) return;
		const viewport = canvasRef.current.querySelector( '[data-embla-viewport]' );
		if ( ! viewport ) return;

		const embla = EmblaCarousel( viewport, { loop: {$loop}, align: '{$align}' } );

		const prevBtn = canvasRef.current.querySelector( '[data-embla-prev]' );
		const nextBtn = canvasRef.current.querySelector( '[data-embla-next]' );
		prevBtn?.addEventListener( 'click', () => embla.scrollPrev() );
		nextBtn?.addEventListener( 'click', () => embla.scrollNext() );

		const dots = Array.from( canvasRef.current.querySelectorAll( '[data-embla-dots] [data-embla-dot]' ) );
		const syncDots = () => {
			const active = embla.selectedScrollSnap();
			dots.forEach( ( dot, i ) => dot.classList.toggle( 'is-active', i === active ) );
		};
		dots.forEach( ( dot, i ) => dot.addEventListener( 'click', () => embla.scrollTo( i ) ) );
		embla.on( 'select', syncDots );
		syncDots();

		return () => embla.destroy();
	}, [ attributes ] );";
			}

			case 'accordion':
				return "
	useEffect( () => {
		if ( ! canvasRef.current ) return;
		canvasRef.current.querySelectorAll( '[class*=\"accordion-trigger\"], [class*=\"accordion__header\"]' ).forEach( ( btn ) => {
			btn.addEventListener( 'click', () => {
				const panel = btn.nextElementSibling;
				const isOpen = btn.getAttribute( 'aria-expanded' ) === 'true';
				btn.setAttribute( 'aria-expanded', String( ! isOpen ) );
				if ( panel ) panel.style.maxHeight = isOpen ? '0' : panel.scrollHeight + 'px';
			} );
		} );
	}, [ attributes ] );";

			default:
				return '';
		}
	}

	private function generate_inspector_controls($fields)
	{
		$jsx = '<PanelBody title="Settings" initialOpen={ true }>';

		foreach ($fields as $field) {
			$key = $field['key'];
			$label = $field['label'];
			$type = $field['type'];

			$jsx .= "\n\t\t\t\t";

			switch ($type) {
				case 'text':
					$jsx .= "<TextControl label=\"$label\" value={ attributes.$key } onChange={ ( val ) => setAttributes( { $key: val } ) } />";
					break;
				case 'textarea':
					$jsx .= "<TextareaControl label=\"$label\" value={ attributes.$key } onChange={ ( val ) => setAttributes( { $key: val } ) } />";
					break;
				case 'range':
					$jsx .= "<RangeControl label=\"$label\" value={ attributes.$key } onChange={ ( val ) => setAttributes( { $key: val } ) } min={ 0 } max={ 100 } />";
					break;
				case 'image':
					$jsx .= "<div className=\"media-control\">
						<label className=\"components-base-control__label\">$label</label>
						<MediaUploadCheck>
							<MediaUpload
								onSelect={ ( media ) => setAttributes( { $key: { url: media.url, alt: media.alt, id: media.id } } ) }
								allowedTypes={ ['image'] }
								value={ attributes.$key ? attributes.$key.id : null }
								render={ ( { open } ) => (
									<Button onClick={ open } variant=\"secondary\">
										{ attributes.$key && attributes.$key.url ? 'Replace Image' : 'Upload Image' }
									</Button>
								) }
							/>
						</MediaUploadCheck>
						{ attributes.$key && attributes.$key.url && (
							<div style={{ marginTop: '10px' }}>
								<img src={ attributes.$key.url } alt={ attributes.$key.alt } style={{ maxWidth: '100%' }} />
								<Button isLink isDestructive onClick={ () => setAttributes( { $key: null } ) }>Remove</Button>
							</div>
						) }
					</div>";
					break;
				case 'number':
					$jsx .= "<TextControl label=\"$label\" type=\"number\" value={ attributes.$key } onChange={ ( val ) => setAttributes( { $key: parseFloat(val) } ) } />";
					break;
				case 'email':
					$jsx .= "<TextControl label=\"$label\" type=\"email\" value={ attributes.$key } onChange={ ( val ) => setAttributes( { $key: val } ) } />";
					break;
				case 'url':
					$jsx .= "<TextControl label=\"$label\" type=\"url\" value={ attributes.$key } onChange={ ( val ) => setAttributes( { $key: val } ) } />";
					break;
				case 'icon':
					$jsx .= "<TextControl label=\"$label (Icon Class)\" value={ attributes.$key } onChange={ ( val ) => setAttributes( { $key: val } ) } />";
					break;
				case 'color':
					$jsx .= "<p style={{ fontWeight: 'bold' }}>$label</p><ColorPalette value={ attributes.$key } onChange={ ( val ) => setAttributes( { $key: val } ) } />";
					break;
				case 'date':
					$jsx .= "<p style={{ fontWeight: 'bold' }}>$label</p><DatePicker currentDate={ attributes.$key } onChange={ ( val ) => setAttributes( { $key: val } ) } />";
					break;
				case 'time':
					$jsx .= "<TextControl label=\"$label\" type=\"time\" value={ attributes.$key } onChange={ ( val ) => setAttributes( { $key: val } ) } />";
					break;
				case 'datetime':
					$jsx .= "<p style={{ fontWeight: 'bold' }}>$label</p><DatePicker currentDate={ attributes.$key } onChange={ ( date ) => setAttributes( { $key: date } ) } />";
					break;
				case 'file':
					$jsx .= "<div className=\"file-control\">
						<label className=\"components-base-control__label\">$label</label>
						<MediaUploadCheck>
							<MediaUpload
								onSelect={ ( media ) => setAttributes( { $key: { url: media.url, id: media.id, filename: media.filename || media.url.split('/').pop() } } ) }
								allowedTypes={ ['application/pdf', 'application/msword', 'application/zip'] }
								value={ attributes.$key ? attributes.$key.id : null }
								render={ ( { open } ) => (
									<Button onClick={ open } variant=\"secondary\">
										{ attributes.$key ? 'Change File' : 'Select File' }
									</Button>
								) }
							/>
						</MediaUploadCheck>
						{ attributes.$key && attributes.$key.url && (
							<div style={{ marginTop: '10px' }}>
								<p>Selected: { attributes.$key.filename }</p>
								<Button isLink isDestructive onClick={ () => setAttributes( { $key: null } ) }>Remove</Button>
							</div>
						) }
					</div>";
					break;
				case 'gallery':
					$jsx .= "<div className=\"gallery-control\">
						<label className=\"components-base-control__label\">$label</label>
						<MediaUploadCheck>
							<MediaUpload
								onSelect={ ( media ) => setAttributes( { $key: media } ) }
								allowedTypes={ ['image'] }
								multiple={ true }
								gallery={ true }
								value={ attributes.$key ? attributes.$key.map( item => item.id ) : [] }
								render={ ( { open } ) => (
									<Button onClick={ open } variant=\"primary\">
										{ attributes.$key && attributes.$key.length > 0 ? 'Edit Gallery' : 'Create Gallery' }
									</Button>
								) }
							/>
						</MediaUploadCheck>
						{ attributes.$key && (
							<div style={{ marginTop: '10px', display: 'flex', flexWrap: 'wrap', gap: '5px' }}>
								{ attributes.$key.map( ( img, i ) => (
									<img key={ i } src={ img.url } style={{ width: '40px', height: '40px', objectFit: 'cover' }} />
								) ) }
							</div>
						) }
					</div>";
					break;
				case 'button':
					$jsx .= "<div className=\"button-control-group\">
						<p style={{ fontWeight: 'bold' }}>$label</p>
						<TextControl label=\"Button Text\" value={ attributes.$key?.text || '' } onChange={ ( val ) => setAttributes( { $key: { ...attributes.$key, text: val } } ) } />
						<TextControl label=\"Button URL\" value={ attributes.$key?.url || '' } onChange={ ( val ) => setAttributes( { $key: { ...attributes.$key, url: val } } ) } />
					</div>";
					break;
				case 'contentEditor':
					// Using a toggle to switch between rich text and HTML view if needed, 
					// but here we just render toggle + basic logic. 
					// For simplicity in PHP generator, we might just use a Textarea for HTML mode and RichText for visual.
					$htmlMode = "is_html_mode_$key";
					$jsx .= "<div className=\"content-editor-control\">
						<ToggleControl
							label=\"Enable HTML Mode\"
							checked={ attributes.$htmlMode }
							onChange={ ( val ) => setAttributes( { $htmlMode: val } ) }
						/>
						{ attributes.$htmlMode ? (
							<TextareaControl label=\"$label (HTML)\" value={ attributes.$key } onChange={ ( val ) => setAttributes( { $key: val } ) } />
						) : (
							<div style={{ border: '1px solid #ccc', padding: '10px' }}>
								<label className=\"components-base-control__label\">$label</label>
								<RichText
									tagName=\"div\"
									value={ attributes.$key }
									onChange={ ( val ) => setAttributes( { $key: val } ) }
								/>
							</div>
						) }
					</div>";
					break;
				case 'relational':
					$jsx .= "<SelectControl 
						label=\"$label (Post ID)\"
						value={ attributes.$key }
						options={ [ { label: 'Select Post...', value: '' } ] }
						onChange={ ( val ) => setAttributes( { $key: val } ) }
						help=\"Dynamic post loading require custom JS hook.\"
					/>";
					break;
				case 'repeater':
					$subFields = isset($field['subFields']) ? $field['subFields'] : [];

					// Helper function for inner controls - simplified for PHP generator
					// Note:Ideally this should match the JS generator's full capability.
					// For now, we inline a basic version or call a helper.
					$inner_jsx = "";
					foreach ($subFields as $subField) {
						$sKey = $subField['key'];
						$sLabel = $subField['label'];
						$sType = $subField['type'];

						switch ($sType) {
							case 'textarea':
								$inner_jsx .= "
									<TextareaControl 
										label=\"$sLabel\"
										value={ item.$sKey || '' }
										onChange={ ( val ) => {
											const newItems = [...attributes.$key];
											newItems[index] = { ...item, $sKey: val };
											setAttributes({ $key: newItems });
										}}
									/>
								";
								break;
							case 'range':
								$inner_jsx .= "
									<RangeControl 
										label=\"$sLabel\"
										value={ item.$sKey }
										onChange={ ( val ) => {
											const newItems = [...attributes.$key];
											newItems[index] = { ...item, $sKey: val };
											setAttributes({ $key: newItems });
										}}
										min={ 0 }
										max={ 100 }
									/>
								";
								break;
							case 'number':
								$inner_jsx .= "
									<TextControl 
										label=\"$sLabel\"
										type=\"number\"
										value={ item.$sKey || '' }
										onChange={ ( val ) => {
											const newItems = [...attributes.$key];
											newItems[index] = { ...item, $sKey: parseFloat(val) };
											setAttributes({ $key: newItems });
										}}
									/>
								";
								break;
							case 'email':
								$inner_jsx .= "
									<TextControl 
										label=\"$sLabel\"
										type=\"email\"
										value={ item.$sKey || '' }
										onChange={ ( val ) => {
											const newItems = [...attributes.$key];
											newItems[index] = { ...item, $sKey: val };
											setAttributes({ $key: newItems });
										}}
									/>
								";
								break;
							case 'url':
								$inner_jsx .= "
									<TextControl 
										label=\"$sLabel\"
										type=\"url\"
										value={ item.$sKey || '' }
										onChange={ ( val ) => {
											const newItems = [...attributes.$key];
											newItems[index] = { ...item, $sKey: val };
											setAttributes({ $key: newItems });
										}}
									/>
								";
								break;
							case 'icon':
								$inner_jsx .= "
									<TextControl 
										label=\"$sLabel (Icon Class)\"
										value={ item.$sKey || '' }
										onChange={ ( val ) => {
											const newItems = [...attributes.$key];
											newItems[index] = { ...item, $sKey: val };
											setAttributes({ $key: newItems });
										}}
									/>
								";
								break;
							case 'color':
								$inner_jsx .= "
									<div className=\"color-control-wrapper\" style={{ marginTop: '10px' }}>
										<p style={{ fontWeight: 'bold', marginBottom: '5px' }}>$sLabel</p>
										<ColorPalette 
											value={ item.$sKey } 
											onChange={ ( val ) => {
												const newItems = [...attributes.$key];
												newItems[index] = { ...item, $sKey: val };
												setAttributes({ $key: newItems });
											}} 
										/>
									</div>
								";
								break;
							case 'date':
								$inner_jsx .= "
									<div className=\"date-control-wrapper\" style={{ marginTop: '10px' }}>
										<p style={{ fontWeight: 'bold', marginBottom: '5px' }}>$sLabel</p>
										<DatePicker 
											currentDate={ item.$sKey } 
											onChange={ ( val ) => {
												const newItems = [...attributes.$key];
												newItems[index] = { ...item, $sKey: val };
												setAttributes({ $key: newItems });
											}} 
										/>
									</div>
								";
								break;
							case 'time':
								$inner_jsx .= "
									<TextControl 
										label=\"$sLabel\"
										type=\"time\"
										value={ item.$sKey || '' }
										onChange={ ( val ) => {
											const newItems = [...attributes.$key];
											newItems[index] = { ...item, $sKey: val };
											setAttributes({ $key: newItems });
										}}
									/>
								";
								break;
							case 'datetime':
								$inner_jsx .= "
									<div className=\"datetime-control-wrapper\" style={{ marginTop: '10px' }}>
										<p style={{ fontWeight: 'bold', marginBottom: '5px' }}>$sLabel</p>
										<DatePicker 
											currentDate={ item.$sKey } 
											onChange={ ( date ) => {
												const newItems = [...attributes.$key];
												newItems[index] = { ...item, $sKey: date };
												setAttributes({ $key: newItems });
											}} 
										/>
									</div>
								";
								break;
							case 'image':
								$inner_jsx .= "
									<div className=\"media-control-wrapper\" style={{ marginTop: '10px' }}>
										<label className=\"components-base-control__label\">$sLabel</label>
										<MediaUploadCheck>
											<MediaUpload
												onSelect={ ( media ) => {
													const newItems = [...attributes.$key];
													newItems[index] = { ...item, $sKey: { url: media.url, id: media.id, alt: media.alt } };
													setAttributes({ $key: newItems });
												}}
												allowedTypes={ ['image'] }
												value={ item.$sKey ? item.$sKey.id : null }
												render={ ( { open } ) => (
													<Button onClick={ open } variant=\"secondary\">
														{ item.$sKey ? 'Change Image' : 'Select Image' }
													</Button>
												) }
											/>
										</MediaUploadCheck>
										{ item.$sKey && item.$sKey.url && (
											<img src={ item.$sKey.url } style={{ maxWidth: '50px', display: 'block', marginTop: '5px' }} alt={ item.$sKey.alt } />
										)}
									</div>
								";
								break;
							case 'file':
								$inner_jsx .= "
									<div className=\"file-control-wrapper\" style={{ marginTop: '10px' }}>
										<label className=\"components-base-control__label\">$sLabel</label>
										<MediaUploadCheck>
											<MediaUpload
												onSelect={ ( media ) => {
													const newItems = [...attributes.$key];
													newItems[index] = { ...item, $sKey: { url: media.url, id: media.id, filename: media.filename || media.url.split('/').pop() } };
													setAttributes({ $key: newItems });
												}}
												allowedTypes={ ['application/pdf', 'application/msword', 'application/zip'] }
												value={ item.$sKey ? item.$sKey.id : null }
												render={ ( { open } ) => (
													<Button onClick={ open } variant=\"secondary\">
														{ item.$sKey ? 'Change File' : 'Select File' }
													</Button>
												) }
											/>
										</MediaUploadCheck>
										{ item.$sKey && item.$sKey.url && (
											<div style={{ marginTop: '5px', fontSize: '12px' }}>
												Selected: { item.$sKey.filename }
												<br/>
												<Button isLink isDestructive onClick={ () => {
													const newItems = [...attributes.$key];
													newItems[index] = { ...item, $sKey: null };
													setAttributes({ $key: newItems });
												}}>Remove</Button>
											</div>
										)}
									</div>
								";
								break;
							case 'gallery':
								$inner_jsx .= "
									<div className=\"gallery-control-wrapper\" style={{ marginTop: '10px' }}>
										<label className=\"components-base-control__label\">$sLabel</label>
										<MediaUploadCheck>
											<MediaUpload
												onSelect={ ( media ) => {
													const newItems = [...attributes.$key];
													newItems[index] = { ...item, $sKey: media };
													setAttributes({ $key: newItems });
												}}
												allowedTypes={ ['image'] }
												multiple={ true }
												gallery={ true }
												value={ item.$sKey ? item.$sKey.map( i => i.id ) : [] }
												render={ ( { open } ) => (
													<Button onClick={ open } variant=\"primary\" isSmall>
														{ item.$sKey && item.$sKey.length > 0 ? 'Edit Gallery' : 'Create Gallery' }
													</Button>
												) }
											/>
										</MediaUploadCheck>
										{ item.$sKey && (
											<div style={{ marginTop: '5px', display: 'flex', flexWrap: 'wrap', gap: '5px' }}>
												{ item.$sKey.map( ( img, i ) => (
													<img key={ i } src={ img.url } style={{ width: '30px', height: '30px', objectFit: 'cover' }} />
												) ) }
											</div>
										) }
									</div>
								";
								break;
							case 'button':
								$inner_jsx .= "
									<div className=\"button-control-group\" style={{ marginTop: '10px', padding: '5px', border: '1px dashed #ddd' }}>
										<p style={{ fontWeight: 'bold', fontSize: '12px' }}>$sLabel</p>
										<TextControl 
											label=\"Text\" 
											value={ item.$sKey?.text || '' } 
											onChange={ ( val ) => {
												const newItems = [...attributes.$key];
												const currentBtn = item.$sKey || {};
												newItems[index] = { ...item, $sKey: { ...currentBtn, text: val } };
												setAttributes({ $key: newItems });
											}} 
										/>
										<TextControl 
											label=\"URL\" 
											value={ item.$sKey?.url || '' } 
											onChange={ ( val ) => {
												const newItems = [...attributes.$key];
												const currentBtn = item.$sKey || {};
												newItems[index] = { ...item, $sKey: { ...currentBtn, url: val } };
												setAttributes({ $key: newItems });
											}} 
										/>
									</div>
								";
								break;
							case 'contentEditor':
								// Simplified content editor for repeater (no toggle to keep it clean, just HTML/Textarea or RichText)
								// RichText inside repeater can be tricky with focus, using Textarea or TextControl is safer for simple usage.
								// Or implementing RichText with care. Let's use RichText but be aware of potential focus issues.
								// Actually, let's stick to Textarea for HTML/Shortcode support or simple RichText.
								$inner_jsx .= "
									<div className=\"content-editor-wrapper\" style={{ marginTop: '10px' }}>
										<label className=\"components-base-control__label\">$sLabel</label>
										<RichText
											tagName=\"div\"
											value={ item.$sKey || '' }
											onChange={ ( val ) => {
												const newItems = [...attributes.$key];
												newItems[index] = { ...item, $sKey: val };
												setAttributes({ $key: newItems });
											}}
											placeholder=\"Enter content...\"
											style={{ border: '1px solid #ccc', padding: '5px', minHeight: '60px' }}
										/>
									</div>
								";
								break;
							case 'relational':
								$inner_jsx .= "
									<SelectControl 
										label=\"$sLabel (Post ID)\"
										value={ item.$sKey }
										options={ [ { label: 'Select Post...', value: '' } ] }
										onChange={ ( val ) => {
											const newItems = [...attributes.$key];
											newItems[index] = { ...item, $sKey: val };
											setAttributes({ $key: newItems });
										}}
										help=\"Dynamic post loading require custom JS hook.\"
									/>
								";
								break;
							default:
								// Text
								$inner_jsx .= "
									<TextControl 
										label=\"$sLabel\"
										value={ item.$sKey || '' }
										onChange={ ( val ) => {
											const newItems = [...attributes.$key];
											newItems[index] = { ...item, $sKey: val };
											setAttributes({ $key: newItems });
										}}
									/>
								";
								break;
						}

					}

					$jsx .= "
						<br />
						<label className=\"components-base-control__label\">$label</label>
						{ ( attributes.$key || [] ).map( ( item, index ) => (
							<div key={ index } className=\"gutenkit-repeater-item\" style={{ padding: '15px', border: '1px solid #e0e0e0', marginBottom: '15px', borderRadius: '4px', background: '#f8f9fa' }}>
								<div style={{ marginBottom: '15px', fontWeight: 'bold', borderBottom: '1px solid #eee', paddingBottom: '10px' }}>Item { index + 1 }</div>
								$inner_jsx
								<div className=\"gutenkit-repeater-controls\" style={{ display: 'flex', justifyContent: 'space-between', marginTop: '10px', paddingTop: '10px', borderTop: '1px solid #eee' }}>
									<div className=\"gutenkit-repeater-move-controls\">
										<Button 
											icon=\"arrow-up-alt2\" 
											label=\"Move Up\"
											isSmall
											variant=\"secondary\"
											disabled={ index === 0 }
											onClick={ () => {
												const newItems = [...attributes.$key];
												const temp = newItems[index];
												newItems[index] = newItems[index - 1];
												newItems[index - 1] = temp;
												setAttributes({ $key: newItems });
											}} 
										/>
										<Button 
											icon=\"arrow-down-alt2\" 
											label=\"Move Down\"
											isSmall
											variant=\"secondary\"
											disabled={ index === attributes.$key.length - 1 }
											style={{ marginLeft: '5px' }}
											onClick={ () => {
												const newItems = [...attributes.$key];
												const temp = newItems[index];
												newItems[index] = newItems[index + 1];
												newItems[index + 1] = temp;
												setAttributes({ $key: newItems });
											}} 
										/>
									</div>
									<Button isDestructive variant=\"link\" isSmall onClick={ () => {
										const newItems = attributes.$key.filter( ( _, i ) => i !== index );
										setAttributes( { $key: newItems } );
									} }>
										Remove Item
									</Button>
								</div>
							</div>
						) ) }
						<Button variant=\"primary\" onClick={ () => {
							const newItems = [ ...( attributes.$key || [] ), {} ];
							setAttributes( { $key: newItems } );
						} }>
							Add New Item
						</Button>
					";
					break;
				default:
					// Fallback for types not strictly handled yet
					$jsx .= "<TextControl label=\"$label (Type: $type)\" value={ attributes.$key } onChange={ ( val ) => setAttributes( { $key: val } ) } />";
					break;
			}
			$jsx .= "<br />";
		}

		$jsx .= "\n\t\t\t</PanelBody>";
		return $jsx;
	}

	private function generate_canvas_preview($template, $fields)
	{
		if (empty($template)) {
			return '<div>Please define a template in the editor.</div>';
		}

		$placeholder = 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA4MDAgNjAwIiB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIj4KICA8cmVjdCB3aWR0aD0iODAwIiBoZWlnaHQ9IjYwMCIgZmlsbD0iI2YxZjVmOSIgLz4KICA8ZyBmaWxsPSIjY2JkNWUxIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgzMjAsIDIyMCkiPgogICAgPHBhdGggZD0iTTM1LjIxNiAxMi43ODRDMzIuOTUxIDEwLjUxOSAzMC4yMDQgOS4zODMgMjcgOS4zODNzLTUuOTUyIDEuMTM2LTguMjE2IDMuNDAxQzE2LjUxOSAxNS4wNDkgMTUuMzgxIDE3Ljc5NiAxNS4zODEgMjFzMS4xMzYgNS45NTEgMy40IDguMjE2QzIxLjA0OSAzMS40ODEgMjMuNzk2IDMyLjYxOSAyNyAzMi42MTlzNS45NTEtMS4xMzYgOC4yMTYtMy40QzM3LjQ4MSAyNi45NTEgMzguNjE5IDI0LjIwNCAzOC42MTkgMjFzLTEuMTM2LTUuOTUxLTMuNC04LjIxNnoiIC8+CiAgICA8cGF0aCBkPSJNMTE1LjY1NCA4Ni4zOEw5Mi44MzIgNTQuNzAxYy0uODItMS4xMzQtMi4yNzItMS45Mi0zLjkwMi0xLjkyLTIuMDY0IDAtMy4yOTMgMS4xMDItMy45ODIgMi4wMjFsLTMxLjE2IDQyLjM2NC0yNS40NC0yOS40NzJhNC45MzUgNC45MzUgMCAwIDAtMy44ODQtMS43OWMtMS45NCAwLTMuNDkyIDEuMTgxLTQuMDU2IDIuMDVMNS4xODcgODUuNzc0di42NTljMCAxNy42NzIgMTQuMzI3IDMyIDMyIDMyaDEwMy40NTNjOC4yODQgMCAxNS4zNy0zLjE1NCAyMC4yMTQtOC42OTRMOTQuOTIgOTMuMjIxYzEuMDk2IDAgMi4xMzYtLjMxNiAzLjAyNS0uODg4Ljc4NC0uNTA1IDEuMzM1LTEuMjIxIDEuNTktMi4wNmwuNTc2LTIuMDFMMTE1LjY1NCA4Ni4zOEoiIC8+CiAgICA8cGF0aCBkPSJNMTQyLjEzMyA3Ljg2N0EyNi41NTYgMjYuNTU2IDAgMCAwIDEyMy4yNjcgMEgzMC43MzNDMTMuNzkyIDAgMCAxMy43OTIgMCAzMC43MzN2NzkuODE4bDkuODY3LTEzLjc2NmMxLjc4My0yLjQ5MyA0Ljc5OC00LjAxNiA3Ljk1LTQuMDE2czQuOTUgMS4xNTggNi43MTIgMy4xMjdMMzkuMjM2IDExNC4yeiIgLz4KICA8L2c+Cjwvc3ZnPg==';

		// We need to construct a JS template string from the HTML
		// Replace {{key}} with ${attributes.key}
		// NOTE: We need to be careful about quotes.

		// Escape backticks in the template because we will wrap it in backticks for JS
		$js_safe_template = str_replace('`', '\`', $template);

		// 1. Handle Repeater & Gallery Loops: {{#key}} content {{/key}}
		// Find all repeater and gallery fields first to know their structure
		$repeater_fields = [];
		$gallery_fields = [];

		foreach ($fields as $field) {
			if ($field['type'] === 'repeater') {
				$repeater_fields[$field['key']] = $field; // Store full field config including subFields
			}
			if ($field['type'] === 'gallery') {
				$gallery_fields[$field['key']] = $field;
			}
		}

		// Regex to find loops
		// Matches {{#key}} or {{#each key}} ... {{/key}} or {{/each}}
		// format: {{#key}} content {{/key}}
		$js_safe_template = preg_replace_callback('/\{\{#(?:each\s+)?(\w+)\}\}(.*?)\{\{\/(?:\1|each)\}\}/s', function ($matches) use ($repeater_fields, $gallery_fields, $placeholder) {
			$loop_key = $matches[1];
			$inner_content = $matches[2];

			$is_repeater = isset($repeater_fields[$loop_key]);
			$is_gallery = isset($gallery_fields[$loop_key]);

			// Check if this repeater/gallery exists in our config
			if (!$is_repeater && !$is_gallery) {
				return $matches[0]; // Return original if not found
			}

			if ($is_gallery) {
				// Handle Gallery Loop
				// Item is the image object { id, url, alt, ... }
				// {{url}} -> ${item.url}
				// {{alt}} -> ${item.alt}
				// {{id}} -> ${item.id}

				$inner_content = str_replace('{{url}}', '${item.url || ""}', $inner_content);
				$inner_content = str_replace('{{alt}}', '${item.alt || ""}', $inner_content);
				$inner_content = str_replace('{{id}}', '${item.id || ""}', $inner_content);

				return "\${ attributes.$loop_key && attributes.$loop_key.map((item, index) => `$inner_content`).join('') }";
			}

			// Handle Repeater Loop
			$sub_fields = $repeater_fields[$loop_key]['subFields'] ?? [];

			// Process inner content for subfields
			foreach ($sub_fields as $sub_field) {
				$sKey = $sub_field['key'];
				$sType = $sub_field['type'];

				// Determine replacement based on type
				// Inside the map, 'item' is the current object
				if ($sType === 'image' || $sType === 'file') {
					$replacement = "\${item.$sKey?.url || '$placeholder'}";
					// Handle Alt/Filename: {{key_alt}}
					$inner_content = preg_replace('/\{\{\s*' . preg_quote($sKey . '_alt', '/') . '\s*\}\}/', "\${item.$sKey?.alt || item.$sKey?.filename || ''}", $inner_content);
				} else {
					$replacement = "\${item.$sKey || ''}";
				}

				// Replace {{subkey}} with ${item.subkey}
				$inner_content = preg_replace('/\{\{\s*' . preg_quote($sKey, '/') . '\s*\}\}/', $replacement, $inner_content);
			}

			// Wrap in map
			return "\${ attributes.$loop_key && attributes.$loop_key.map((item, index) => `$inner_content`).join('') }";
		}, $js_safe_template);


		// 2. Handle Top-Level Fields
		foreach ($fields as $field) {
			$key = $field['key'];
			$type = $field['type'];

			// Skip if it's a repeater/gallery that we might have already processed (or don't want to replace top-level)
			if ($type === 'repeater' || $type === 'gallery')
				continue;

			if ($type === 'image' || $type === 'file') {
				// We'll replace {{key}} with ${attributes.$key?.url || 'placeholder'}
				$replacement = "\${attributes.$key?.url || '$placeholder'}";
				// Handle Alt: {{key_alt}}
				$replacement_alt = "\${attributes.$key?.alt || attributes.$key?.filename || ''}";
				$js_safe_template = preg_replace('/\{\{\s*' . preg_quote($key . '_alt', '/') . '\s*\}\}/', $replacement_alt, $js_safe_template);
			} elseif ( $type === 'button' ) {
				// Renders a live anchor tag in the canvas preview
				$replacement = "<a href=\"\${attributes.$key?.url || '#'}\" class=\"gk-btn\">\${attributes.$key?.text || 'Click Here'}</a>";
			} else {
				$replacement = "\${attributes.$key || ''}";
			}

			// Flexible regex for {{ key }} with spaces
			$js_safe_template = preg_replace('/\{\{\s*' . preg_quote($key, '/') . '\s*\}\}/', $replacement, $js_safe_template);
		}

		// Return the dangerouslySetInnerHTML
		// "dangerouslySetInnerHTML={{ __html: `...` }}"
		return "<div dangerouslySetInnerHTML={{ __html: `$js_safe_template` }} />";
	}
	// generate_render_php() removed in Task 4 — now handled by Node.js (generate-block-code-multi.js)

	// =========================================================
	// Infrastructure helpers: filesystem, logging
	// =========================================================

	/**
	 * Returns an initialised WP_Filesystem instance (direct method for local sites).
	 * Falls back to null if WP_Filesystem is unavailable.
	 */
	private function get_filesystem()
	{
		global $wp_filesystem;
		if (empty($wp_filesystem)) {
			if (!function_exists('WP_Filesystem')) {
				require_once ABSPATH . 'wp-admin/includes/file.php';
			}
			WP_Filesystem();
		}
		return ($wp_filesystem instanceof WP_Filesystem_Base) ? $wp_filesystem : null;
	}

}
